export const icons = {
  send: require('./source/send.png'),
  back: require('./source/arrow-left.png'),
  bullet: require('./source/bullet.png'),
  close: require('./source/ic_close.png'),
  plus: require('./source/ic_plus.png'),
  home: require('./source/ic_home.png'),
  heart: require('./source/ic_heart.png'),
  search: require('./source/ic_search.png'),
  user: require('./source/ic_user.png'),
  arrow_down: require('./source/arrow_down.png'),
  check: require('./source/check.png'),
  google: require('./source/google.png'),
  facebook: require('./source/facebook.png'),
  shopping_bag: require('./source/shopping-bag.png'),
  outstanding: require('./source/outstanding.png'),
  crown: require('./source/crown.png'),
  star: require('./source/star.png'),
  diamond: require('./source/diamond.png'),
  circled_menu: require('./source/circled-menu.png'),
  ic_shop_gold: require('./source/ic_shop_gold.png'),
  play: require('./source/play.png'),
};

export type IconTypes = keyof typeof icons;
