export const images = {
  bg_wallpaper: require('./source/bg.png'),
  default: require('./source/default.png'),
  succeeded: require('./source/succeeded.png'),
  expo_market: require('./source/expo_market.png'),
  online_transaction: require('./source/online_transaction.png'),
  trust_supplier: require('./source/trust_supplier.png'),
  potential_supplier: require('./source/potential_supplier.png'),
  user_default: require('./source/user_default.png'),
  bestseller: require('./source/bestseller.png'),
  flash_sale: require('./source/flash_sale.png'),
  shop_header: require('./source/shop_header.png'),
  wallet: require('./source/wallet.png'),
  amex_inactive: require('./source/amex_inactive.png'),
  amex_active: require('./source/amex_active.png'),
  mastercard_inactive: require('./source/mastercard_inactive.png'),
  mastercard_active: require('./source/mastercard_active.png'),
  visa_inactive: require('./source/visa_inactive.png'),
  visa_active: require('./source/visa_active.png'),
  JCB_inactive: require('./source/JCB_inactive.png'),
  JCB_active: require('./source/JCB_active.png'),
  location: require('./source/location.png'),
  empty_product: require('./source/empty_product.png'),
  GB: require('./source/GB.png'),
  VN: require('./source/VN.png'),
  empty_order: require('./source/empty_order.png'),
  empty_voucher: require('./source/empty_voucher.png'),
};

export type ImageTypes = keyof typeof images;
